name: Jacoco test report

on:
  pull_request:
  push:
    branches:
      - coverage/sonar_scan_multimodule

jobs:
  jacoco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run jacoco
        run: ./gradlew jacocoTest

      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: '**/build/reports/jacoco'

      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: '**/build/reports/jacoco'
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info
      - name: Jacoco report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build jacocoTestReport sonarqube
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          files: '**/testDebugUnitTestCoverage.xml'
