name: Jacoco test report

on:
  pull_request:
  push:
    branches:
      - coverage/unit_test_case

jobs:
  jacoco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run jacoco
        run: ./gradlew jacocoTest

      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: '**/build/reports/jacoco'

      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: '**/build/reports/jacoco'
      - name: Jacoco report
        run: ./gradlew build jacocoTestReport sonarqube
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          files: '**/testDebugUnitTestCoverage.xml'
